git config --global user.name "Raphael-otto"
git config --global user.email "Raphaelotto.RO@gmail.com"
git config  user.name "Raphael-otto"
git config  user.email "Raphaelotto.RO@gmail.com"
git config  user.name "Raphael-otto"
git config  user.email "Raphaelotto.RO@gmail.com"
